version: '3.8'
services:
  postgres:
    container_name: strapi-postgres-db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $DB_USER" ]
      interval: 5s
      timeout: 5s
      retries: 5
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - '5432:5432'

volumes:
  strapi-data:
